# Generated by Django 3.2.6 on 2022-06-21 05:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='team',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=250)),
                ('last_name', models.CharField(max_length=250)),
                ('designation', models.CharField(max_length=250)),
                ('photo', models.ImageField(upload_to='photos/%y/%m/%d')),
                ('facebook_link', models.URLField(max_length=250)),
                ('tweeter_link', models.URLField(max_length=250)),
                ('google_plus_link', models.URLField(max_length=250)),
                ('create_date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
